services:
  server:
    build: .
    restart: always
    volumes:
      - upload-files:/app/upload-files
    depends_on:
      - mysql
    env_file: .env
    ports:
      - ${APP_PORT}:${APP_PORT}

volumes:
  upload-files:
